# Generated by Django 4.1.7 on 2023-03-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_outlet", "0002_book_author_book_is_best_selling_book_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
